@startuml arquitectura
package cinterodiaz.mastermind #DDDDDD { }
cinterodiaz.mastermind .down.> cinterodiaz.mastermind.views
cinterodiaz.mastermind .down.> cinterodiaz.mastermind.models

package cinterodiaz.mastermind.models #DDDDDD { }
cinterodiaz.mastermind.models .down.> cinterodiaz.mastermind.types
package cinterodiaz.mastermind.types #DDDDDD { }
package java.util{ }
cinterodiaz.mastermind.models .down.> java.util

package cinterodiaz.utils #DDDDDD { }
package java.io{ }
cinterodiaz.utils .down.> java.io

package cinterodiaz.mastermind.views #DDDDDD { }
cinterodiaz.mastermind.views .down.> cinterodiaz.mastermind.models
cinterodiaz.mastermind.views .down.> cinterodiaz.mastermind.types
cinterodiaz.mastermind.views .down.> cinterodiaz.utils
@enduml